name: مباريات

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

# ----------------------------------------
# تمت إضافة هذا الجزء لإعطاء صلاحية الرفع
permissions:
  contents: write
# ----------------------------------------

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm init -y
          npm pkg set type="module"
          npm install axios puppeteer
          npx puppeteer browsers install chrome

      - name: Run Scraper
        run: node index.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add matches.json
          git commit -m "Update matches data [skip ci]" || exit 0
          git push
